Update xiaomi_touch.c
xiaomi_touch: Fix error cause a function declaration is deprecated

../kernel/drivers/input/touchscreen/mediatek/xiaomi/xiaomi_touch.c:136:37: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct class *get_xiaomi_touch_class()
                                    ^
                                     void
../kernel/drivers/input/touchscreen/mediatek/xiaomi/xiaomi_touch.c:141:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device *get_xiaomi_touch_dev()
                                   ^
                                    void
2 errors generated.